const files=['01_Hons_Family','02_Shadow_Family','03_Hollow_Circle','04_Neon_House','05_Velvet_Order','06_Night_Collective','07_Silver_Guild','08_Crimson_Family','09_Static_Society','10_Ghost_Network'];
const mods=await Promise.all(files.map(f=>import(`./clubs/${f}.js`)));
const clubs=mods.map(m=>m.default);
const $=x=>document.getElementById(x), stage=$('mapStage'), canvas=$('mapCanvas'), ctx=canvas.getContext('2d'); let W,H,drag=false,last,selected=null;
const view={x:0,y:0,zoom:.72}; const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(0)+'K':n;
function size(){W=canvas.width=stage.clientWidth;H=canvas.height=stage.clientHeight} addEventListener('resize',size);size();
function pos(c){return{x:W/2+((c._x??c.x)-view.x)*view.zoom,y:H/2+((c._y??c.y)-view.y)*view.zoom}}
function wiki(w){return(Array.isArray(w)?w:[w]).map(s=>`<div class="wiki-line">()&lt; ${String(s).replaceAll('<','&lt;').replaceAll('>','&gt;')} &gt;()</div>`).join('')}
function profile(c){$('profileContent').innerHTML=`<div class="profile-hero" style="background-image:${c.backgroundURI?`url('${c.backgroundURI}')`:'linear-gradient(135deg,#06385a,#020916)'}"><div class="profile-head"><div class="profile-tag">CLUB // ${c.id}</div><div class="profile-name">${c.name}</div></div></div><div class="profile-body"><div class="profile-stats"><div class="pstat"><b>${fmt(c.people)}</b><span>PEOPLE</span></div><div class="pstat"><b>${fmt(c.active)}</b><span>ACTIVE NOW</span></div></div><div class="wiki-title">WIKI // PROFILE</div><div class="wiki">${wiki(c.wiki)}</div><div class="wiki-title">HOVER // PREVIEW</div><div class="wiki">${c.hoverText}</div><div class="editor"><div class="editor-title">EDIT THIS CLUB</div><label>Name<input id="eN" value="${c.name}"></label><label>People<input id="eP" type="number" value="${c.people}"></label><label>Active<input id="eA" type="number" value="${c.active}"></label><label>Hover<textarea id="eH">${c.hoverText}</textarea></label><label>Wiki — one entry per line<textarea id="eW">${(Array.isArray(c.wiki)?c.wiki:[c.wiki]).join('\n')}</textarea></label><label>Color<input id="eC" value="${c.color}"></label><label>Background URI<input id="eB" value="${c.backgroundURI||''}"></label><button id="save">SAVE PROFILE</button></div></div>`;$('save').onclick=()=>{c.name=$('eN').value;c.people=+$('eP').value;c.active=+$('eA').value;c.hoverText=$('eH').value;c.wiki=$('eW').value.split(/\n+/).filter(Boolean);c.color=$('eC').value;c.backgroundURI=$('eB').value;profile(c)}}
function open(c){selected=c;profile(c);$('profilePanel').classList.remove('closed');view.x=c.x;view.y=c.y}
function draw(){ctx.clearRect(0,0,W,H);for(let i=0;i<clubs.length;i++)for(let j=i+1;j<clubs.length;j++){let a=pos(clubs[i]),b=pos(clubs[j]);ctx.strokeStyle='rgba(50,190,255,.16)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}clubs.forEach(c=>{let p=pos(c);ctx.shadowBlur=24;ctx.shadowColor=c.color;ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(p.x,p.y,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#dffaff';ctx.font='10px monospace';ctx.fillText(c.name,p.x+14,p.y+3)});requestAnimationFrame(draw)} requestAnimationFrame(draw);
let t=0,old=performance.now();function move(n){t+=(n-old)/1000;old=n;clubs.forEach((c,i)=>{c._x=c.x+Math.sin(t*.06+i)*18;c._y=c.y+Math.cos(t*.05+i)*13});requestAnimationFrame(move)}requestAnimationFrame(move);
canvas.addEventListener('pointerdown',e=>{drag=true;last=e;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){view.x-=(e.clientX-last.clientX)/view.zoom;view.y-=(e.clientY-last.clientY)/view.zoom;last=e}});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('click',e=>{if(drag)return;let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,c=clubs.find(c=>Math.hypot(pos(c).x-x,pos(c).y-y)<20);if(c)open(c)});canvas.addEventListener('wheel',e=>{e.preventDefault();view.zoom=Math.max(.25,Math.min(2.2,view.zoom*(e.deltaY<0?1.12:.89)))},{passive:false});
$('enterBtn').onclick=()=>{const q=$('familyInput').value.trim().toLowerCase(),c=clubs.find(c=>c.name.toLowerCase()===q);if(c){$('warning').classList.add('hidden');$('app').classList.remove('hidden');open(c)}else $('warningError').textContent='FAMILY NOT FOUND — CHECK THE NAME.'};$('familyInput').onkeydown=e=>{if(e.key==='Enter')$('enterBtn').click()};$('closePanel').onclick=()=>$('profilePanel').classList.add('closed');$('resetBtn').onclick=()=>{if(selected){view.x=selected.x;view.y=selected.y}else{view.x=0;view.y=0}};$('zoomIn').onclick=()=>view.zoom=Math.min(2.2,view.zoom*1.2);$('zoomOut').onclick=()=>view.zoom=Math.max(.25,view.zoom/1.2);$('zoomReset').onclick=()=>view.zoom=.72;$('statClubs').textContent=clubs.length;$('clubCount').textContent=clubs.length;$('statPeople').textContent=fmt(clubs.reduce((a,c)=>a+c.people,0));
